# Application Configuration
spring.application.name=mongo-postgres-migrator

# Custom Migration Settings
migration.source.mongodb-name=source
migration.target.postgres-db-name=target

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/dummy

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=5000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.open-in-view=false

# Spring Batch Configuration
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true

# Tell Spring Boot NOT to start a web server (Tomcat)
spring.main.web-application-type=none

# Logging Configuration
logging.level.root=INFO
logging.level.org.springframework.batch=INFO

# Custom Migration Rules
migration.chunk-size=5000
migration.fetch-size=1000
migration.threads=4
migration.retry-limit=3
migration.skip-limit=100
migration.verify-counts=true
migration.continue-on-error=true

# Specify which profile you want to activate
#spring.profiles.active=dev

# Define your migration pipeline order here (no spaces after commas)
migration.tables=customers,people
